### PR TITLE
Update docs and contact

### PR DESCRIPTION
**Pull request by adeolaawoyemi**
Update contact details and copyright. Also added workflow for testing.

### CODE REVIEW

**Comment by adeolaawoyemi** [comment]
@renderorange FYI, I've made some changes to update the contact details so others can find me easier in future.

**Comment by blainemotsinger** [comment]
👍 

sounds good, I'll roll up a new release for 0.33.

**Comment by blainemotsinger** [comment]
oh, looks like you already did :)

**Comment by adeolaawoyemi** [comment]
Yep. Thanks. ;)

**Pull request merged**
