### PR TITLE
Version 0.32

### PR DESCRIPTION
**Pull request by blainemotsinger**

### CODE REVIEW

**Review by adeolaawoyemi — APPROVED** [review]
Thanks @renderorange. Looks good to me.

**Comment by blainemotsinger** [comment]
@renatocron 

> Multiple places on my tests I used the code like this:
> 
> $t->post_ok( 'endpoint', form => {
> key1 => $variable1,
> key2 => fake_sentences(2)->(),
> key3 => 1,
> );
> 
> I think the fix should be on Data::Fake but I'll post this here because this may help someone on future, because the errors this generated is very strange (keys get added randomly on the hash)

I'm not quite understanding, `keys get added randomly on the hash`; could you elaborate on what you're expecting to see that should or shouldn't be happening?

The following example is outputting what I expect, in scalar context.

```
#!/usr/bin/env perl

use strict;
use warnings;

use Data::Fake qw/Text/;
use Data::Dumper ();

my $one = {
    two_words => fake_words(2)->(),
    two_sentences => fake_sentences(2)->(),
    two_paragraphs => fake_paragraphs(2)->(),
};

print Data::Dumper::Dumper $one;

my $variable1 = 'ONE';
my $two = {
    key1 => $variable1,
    key2 => fake_sentences(2)->(),
    key3 => 1,
};

print Data::Dumper::Dumper $two;

__END__

$t->post_ok(
    'endpoint',
    form => {
        key1 => $variable1,
        key2 => fake_sentences(2)->(),
        key3 => 1,
);
```
```
blaine@base ~/tmp $ perl test_data_fake_text.pl
$VAR1 = {
          'two_paragraphs' => 'At quibusdam ducimus minima eveniet architecto voluptatem. Sit officia et nihil soluta qui iste. Ab molestiae et velit. Eum quaerat ex velit totam. Dignissimos consectetur ut magni voluptatem quia. Id impedit quam consequatur dolor.

Fuga dolorem animi voluptate nobis dignissimos et. Aut quisquam omnis quis sit voluptatem. Voluptas necessitatibus facilis quis quia. Aut quasi laudantium et fuga sint dolorum reprehenderit fuga. Est amet ex nihil dolorem quae sapiente sunt.',
          'two_sentences' => 'Doloribus quod eum recusandae. Dolores qui neque vitae sint qui laboriosam et repellat.',
          'two_words' => 'fuga totam'
        };
$VAR1 = {
          'key2' => 'Animi numquam dolorem voluptatum et exercitationem. Qui qui reiciendis laudantium esse exercitationem.',
          'key3' => 1,
          'key1' => 'ONE'
        };
```

**Comment by blainemotsinger** [comment]
@renatocron `keys get added randomly on the hash` - are you talking about how the keys are returned randomly?

like this
```
$VAR1 = {
          'key2' => 'Animi numquam dolorem voluptatum et exercitationem. Qui qui reiciendis laudantium esse exercitationem.',
          'key3' => 1,
          'key1' => 'ONE'
        };
```
```
$VAR1 = {
          'key1' => 'ONE',
          'key2' => 'Atque adipisci et provident perferendis natus dignissimos aspernatur. Repellendus officia et vel.',
          'key3' => 1
        };
```
```
$VAR1 = {
          'key3' => 1,
          'key2' => 'Qui consequatur molestiae et. Ipsam ratione deserunt sequi velit eum.',
          'key1' => 'ONE'
        };
```

**Comment by renatocron** [comment]
Hi, Blaine, maybe you are using Data::Fake 0.06 that is already patched 🙂

I'm on my phone right now so I can't test your code, but for the extra keys
I meant that the content returned by fake_words / fake_sentences in list
context started expanding into the list creating new elements instead of
returning single scalar

**Comment by renatocron** [comment]
https://github.com/dagolden/Data-Fake/issues/13#issuecomment-786350137

**Comment by blainemotsinger** [comment]
> [dagolden/Data-Fake#13 (comment)](https://github.com/dagolden/Data-Fake/issues/13#issuecomment-786350137)
> […](#)

Ah makes sense.  Storing into a hash would be list context.

**Pull request merged**
